### PR TITLE
Increased `db import` retry count and delay

### PR DESCRIPTION
**Pull request by forana**

### CODE REVIEW

**Comment by forana** [comment]
@bartelsb could you take a look at this? ;)

**Comment by bartelsb** [comment]
@bjamesvDatica able to test this out?

@forana can you pull the latest changes from the release branch and resolve any merge conflicts? Thanks for the contribution!

**Comment by forana** [comment]
@bartelsb @bjamesvDatica  I cannot - I don't have permissions on this repo anymore (for obvious reasons). Just noticed this was still open from early november and figured it might be something you (@anthonypleshek ) cared about.

**Comment by forana** [comment]
Closing this out so it stops showing up in my lists - you should still have the branch if you still want it ;)

**Pull request closed without merging**
